### ISSUE TITLE
page to get key is not showing 

### ISSUE THREAD

**Issue by DMTarmey** [isi-metaphor/lcc-service#24]
https://[user.gurobi.com](https://user.gurobi.com/download/licenses/free-academic)/download/licenses/free-academic

Hmmm… can't reach this pageCheck if there is a typo in user.gurobi.com.
If spelling is correct, [try running Windows Network Diagnostics](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by jgordon** [comment]
Gurobi have updated their site in the past five years. Go to https://www.gurobi.com/features/academic-named-user-license/
